### ISSUE TITLE
Can't set `currentItem`

### ISSUE THREAD

**Issue by jonathanlinford** [tommybuonomo/dotsindicator#95] opened 2020-07-25 01:15 UTC
You can set the current page in a viewPager by
```
viewPager.currentItem
```
The dots remain on the prior index until the viewpager is touched. Is there any way to set a `currentItem` on the dots indicator?

**Comment by Raingava** [comment] 2021-01-12 06:47
Hello! The solution to this problem is in this [issue](https://github.com/tommybuonomo/dotsindicator/issues/68)

**Comment by i4guar** [comment] 2021-06-04 19:29
I had exactly that issue with the WormDotsIndicator but know I tried the "normal" DotsIndicator and everything works as expected.

**Comment by saidmotya** [comment] 2022-01-12 12:27
any solution for that ?

**Comment by tommybuonomo** [comment] 2022-04-30 16:11
Duplicate of #139

**Comment by tommybuonomo** [comment] 2022-04-30 18:13
Hello, thanks for your contribution !
This issue is now fixed in the new version `4.3`
Thanks 🔥

**Closed by tommybuonomo** 2022-04-30 18:13 UTC
Labels: bug
