### ISSUE TITLE
Get incorrect width of the selected dot when seeking pager programmatically

### ISSUE THREAD

**Issue by kenilt** [tommybuonomo/dotsindicator#85] opened 2020-05-04 07:09 UTC
I put the indicator below the view pager, both of them are one item of the recycler view. And the pager was scroll by an auto scroller, it will seek view pager to the next page every 4 seconds. For the first time, it was shown correctly, but sometimes later, the selected dots just got the correct color but got the wrong width. It happens very often, just use my app in 2-5 minutes, and it happens. How can I prevent this bug happen?

Image: 
![Screen Shot 2020-05-04 at 13 57 26](https://user-images.githubusercontent.com/3811063/80942920-30594880-8e10-11ea-9e91-4100ac084275.png)

**Comment by tommybuonomo** [comment] 2022-04-30 16:48
Duplicate of #66

**Comment by tommybuonomo** [comment] 2022-04-30 18:13
Hello, thanks for your contribution !
This issue is now fixed in the new version `4.3`
Thanks 🔥

**Closed by tommybuonomo** 2022-04-30 18:13 UTC
Labels: bug
