### ISSUE TITLE
For Custom buildTypes Not Import

### ISSUE THREAD

**Issue by rohitPagare** [tommybuonomo/dotsindicator#170] opened 2023-04-19 21:26 UTC
When i create custom build type another than debug or release like  qa(Qaulity Analysis)
it will through exception 

FAILURE: Build completed with 11 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:dataBindingMergeDependencyArtifactsStage'.
> Could not resolve all files for configuration ':app:stageCompileClasspath'.
   > Could not resolve com.tbuonomo:dotsindicator:4.3.
     Required by:
         project :app
      > No matching variant of com.tbuonomo:dotsindicator:4.3 was found. The consumer was configured to find an API of a component, preferably optimized for Android, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'stage', attribute 'com.android.build.api.attributes.AgpVersionAttr' with value '7.4.2' but:

**Comment by bhavesh3005sharma** [comment] 2023-05-09 14:36
I am also facing the same issue. Does anyone looking into this please add updates.

**Comment by LinasSkardzius** [comment] 2023-06-05 06:58
The same issue :(

**Comment by fulcrum6378** [comment] 2023-06-24 20:49
Temporarily we can use this:
For Kotlin:
```kotlin
    buildTypes {
        create("debuggee") {
            ...
            matchingFallbacks += listOf("debug")
        }
    }
```
For Groovy:
```groovy
    buildTypes {
        debuggee {
            ...
            matchingFallbacks = ['debug']
        }
    }
```

The publisher must publish a new version with **a SINGLE VARIANT**! so that we won't need to use the trick above.
Explained more in here: https://github.com/tommybuonomo/dotsindicator/issues/178

**Comment by tommybuonomo** [comment] 2024-11-21 12:58
Duplicate of https://github.com/tommybuonomo/dotsindicator/issues/178

**Closed by tommybuonomo** 2024-11-21 12:58 UTC
