### ISSUE TITLE
Arabic RTL not working

### ISSUE THREAD

**Issue by irshadir7** [tommybuonomo/dotsindicator#51] opened 2019-08-28 08:55 UTC
English layout working fine, but when changing the language into Arabic it showing only one dots

**Comment by tommybuonomo** [comment] 2019-09-03 12:05
Duplicate of #32

**Closed** 2019-09-05 07:25 UTC
Labels: bug, help wanted

**Comment by tommybuonomo** [comment] 2019-09-05 07:27
Hi @irshadir7,
Can you please try with the new version `4.1` ?
Thanks
