### ISSUE TITLE
Wormdotsindicator.kt images clicklistener not working on image number beyond 6

### ISSUE THREAD

**Issue by sayurabh** [tommybuonomo/dotsindicator#147] opened 2022-05-01 02:37 UTC
It is ok if u dont want to understand ur code fault ,this problem i mentioned is real when running viewpager i noticed that if images are beyond 6 dots will show but clicklistener will move to 0 on dot number 7 click u can reproduce this problem on ur own and can check and pls note viewpager it itself a preview no problem i m preparing java version of ur code with this critical bug fix as i domt know kotlin.

**Comment by tommybuonomo** [comment] 2022-05-01 12:19
Hey @sayurabh 
Please provide a screencast of the issue using the last `4.3` version, I can't reproduce what you describing
I'll close the issue again if there is no more info about the issue
Thanks

**Comment by Maxr1998** [comment] 2024-09-22 18:49
I wonder if this is related to the broken clickable attribute that was fixed in #168.

**Closed** 2024-09-28 16:25 UTC
Labels: waiting_for_closing, need info
