### ISSUE TITLE
Support for large number of view pager items

### ISSUE THREAD

**Issue by VGJohn** [tommybuonomo/dotsindicator#48] opened 2019-07-15 11:53 UTC
Currently the worm dot indicator gets cut off at the end if there are more view pager items then can fit in the width of the dot indicator. Can you wrap the dots or maybe stay on the middle dot until it make sense to start scrolling to the last dot again?

**Comment by tommybuonomo** [comment] 2019-08-31 11:36
Duplicate of #45

**Closed** 2022-04-30 16:17 UTC
Labels: improvement

**Comment by KoTius** [comment] 2022-07-21 17:00
@tommybuonomo Hey. Could you please hint how the issue is resolved?
