### ISSUE TITLE
Move the indicator by a button click not pager

### ISSUE THREAD

**Issue by TalkwondoMint** [tommybuonomo/dotsindicator#199] opened 2024-08-27 08:15 UTC
I want to implement the indictor to move with a button click.
i have version 5.

i looked at the library and try to move it by the fucntion within:
```
 Button(
                onClick = {
                    coroutineScope.launch {
                        pagerState.animateScrollToPage(nextPage + 1)
                    }
                }
        ) {
            Text("click to skip")
        }
```
but it does not work... any other way?

**Comment by tommybuonomo** [comment] 2024-11-20 21:48
Hello @TalkwondoMint , I can't reproduce, the `animateScrollToPage` method is working well on my side.

**Comment by tommybuonomo** [comment] 2024-11-20 21:49
I'll close this issue for now. Please provide more information if needed

**Closed by tommybuonomo** 2024-11-20 21:49 UTC
