### ISSUE TITLE
Dot indicator moves to wrong position 

### ISSUE THREAD

**Issue by GalatiaPar** [tommybuonomo/dotsindicator#25] opened 2019-01-25 09:09 UTC
In my case I have a view pager adapter and every item is clickable opening another activity. In my list I only have 2 items. When I swipe to the second, click on it (opens the activity), and then finish the activity, the dots show wrong. While, it should show the second as selected, it shows the first one as selected.

**Comment by abrahamturing** [comment] 2019-03-22 15:04
I am not sure but my situation might also be related. When I add a new page to the view pager, the indicator shows up an extra dot, but the selected dot moves to the first one. When I change the page, it corrects itself.

IMO, the problem seems to originate from `setUpDotsAnimators`. Why do you remove the listener and add it again if a listener already exists? The following call moves the selected dot to the beginning, IMHO:

```
this.pageChangedListener.onPageScrolled(0, 0.0F, 0);
```

**Comment by tommybuonomo** [comment] 2019-08-31 11:41
Hi @GalatiaPar @abrahamturing,
Can you please try with the last version `4.0` ?
Thanks

**Comment by tommybuonomo** [comment] 2022-04-30 16:14
Duplicate of #139

**Closed** 2022-04-30 16:14 UTC
Labels: waiting_for_closing
