### ISSUE TITLE
AAPT2 error

### ISSUE THREAD

**Issue by hadiahmadi77** [tommybuonomo/dotsindicator#10] opened 2018-06-27 17:55 UTC
when I want to implement it its say AAPT2 error before building

**Comment by tommybuonomo** [comment] 2018-06-27 18:55
Hi @hadiahmadi77,

Which version of the android gradle plugin are you using ? 

``` Gradle
dependencies {
    classpath "com.android.tools.build:gradle:???"
}
```

**Comment by hadiahmadi77** [comment] 2018-06-27 18:59
classpath 'com.android.tools.build:gradle:3.1.3'

**Comment by tommybuonomo** [comment] 2018-06-27 19:10
Are you using the sample from the directory or an external project ?
Can you add a stacktrace please ?

**Comment by tommybuonomo** [comment] 2018-07-27 17:43
Duplicate of #14

**Closed** 2018-08-31 12:37 UTC
