### ISSUE TITLE
Select particular position of dot

### ISSUE THREAD

**Issue by akankshapaul048** [tommybuonomo/dotsindicator#57] opened 2019-09-12 10:39 UTC
View Pager + WormDotsIndicator
The viewpager is selected to current item (which can be any position), but I am not able to select the dot indicator to that position of viewpager programatically.

![image](https://user-images.githubusercontent.com/35328127/64777409-b968fa00-d577-11e9-98d1-3820926d34d2.png)

**Comment by tommybuonomo** [comment] 2019-09-26 11:58
Hi @akankshapaul048 ,
If you call `setCurrentItem()` on your ViewPager, the dots will automatically refresh

**Comment by akankshapaul048** [comment] 2019-10-03 07:28
Well i did that but no changes

**Comment by edChori** [comment] 2019-10-24 16:54
Try this
Handler().postDelayed({viewPager.setCurrentItem(1, true)}, 100)

**Comment by oliverspryn** [comment] 2019-11-15 16:13
Correct, this is still a problem, unless you setCurrentItem with an animation.

**Comment by vkotovv** [comment] 2019-12-25 14:25
@tommybuonomo any updates on this?

**Comment by SamadiPour** [comment] 2020-01-07 03:23
Handler().postDelayed({viewPager.setCurrentItem(1, true)}, 75) worked but i want it without this!
is there any other way?

**Comment by wachidsusilo** [comment] 2020-06-07 08:23
This worked for me:

`private boolean onStart = true;
@Override
    public void onWindowFocusChanged(boolean hasFocus) {
        if(onStart){
            onStart = false;
            viewPager.setCurrentItem(pagerPosition, false);
        }
    }`

**Comment by krodyrobi** [comment] 2021-03-16 17:08
Hello, we've hit this as well.

Both the Spring and Worm implementations have the same buggy behavior, on a dark mode switch it selects the 1'st dot but the adapter reports position 3 as the currently active item.
It does not happen on the Dots one, and that is a shame as Worm is so cool.

Debugging the `override fun onPageScrolled(selectedPosition: Int, nextPosition: Int, positionOffset: Float)` callback of worm we see the correct nextPosition but since the dots are not present (only 1 is rendered) it cannot compute the offset to scroll to.

`vp.setCurrentItem(pos, smooth)` only works correctly for Dots not for the other 2.
In our case we use flow and no matter the delay we use we cannot get it to work.

Dot state recovers on next / prev page navigations or on adapter changes.
Can you guys have a look at it?

**Comment by AntonShinkaretsky** [comment] 2021-06-17 10:17
It's still the problem. Indicator doesn't update it's state correctly, and I don't see a way to set currentItem manually

**Comment by tommybuonomo** [comment] 2022-04-30 14:50
Duplicate of #126

**Comment by tommybuonomo** [comment] 2022-04-30 16:25
Hello there, thanks everyone for your contribution
This will be fixed in the `4.3` release

**Closed by tommybuonomo** 2022-04-30 16:25 UTC
Labels: bug
