### ISSUE TITLE
refreshDots not called when ListAdapter.submitList

### ISSUE THREAD

**Issue by li2** [tommybuonomo/dotsindicator#84] opened 2020-04-19 10:37 UTC
I use `androidx.recyclerview.widget.ListAdapter` and call `submitList` to update recyclerView, however, the dots were not showing until I call `notifyDataSetChanged` instead. 

```kotlin
 fun setViewPager2(viewPager2: ViewPager2) {
   viewPager2.adapter!!.registerAdapterDataObserver(object : AdapterDataObserver() {
     override fun onChanged() {
       super.onChanged()
       // I added breakpoint here,
       // and this callback is not trriggered when call submitList
       refreshDots()
     }
   })
 }
```

**Comment by dsawenko** [comment] 2020-04-25 17:26
I've got the same issue with ListAdapter. When calling submitList to push the data to the ViewPager2's adapter, no dots are displayed until notifyDatasetChanged() is called.

**Comment by tommybuonomo** [comment] 2022-04-30 16:30
Duplicate of #109 #84 #78

**Closed by tommybuonomo** 2022-04-30 16:30 UTC
Labels: bug
